import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// GENERATED by the OpenAPI plugin (docusaurus gen-api-docs) from docs/openapi.json — the operation
// pages + their grouped sidebar. Composed under `api-reference` below, after the Get Started intro.
import apiSidebar from './docs/api-reference/sidebar';
// HAND-AUTHORED net-new section sidebars (Agent / Memory — phases C4/C4b). Spread in below so the
// legacy-derived sidebars and the authored ones live in one config. Edit sidebars-authored.ts, not here.
import authoredSidebars, {authoredAdditions} from './sidebars-authored';

/**
 * GENERATED by docs/rewrite/gen-sidebars.cjs from the approved page map — do not hand-edit.
 * Re-run: node docs/rewrite/gen-sidebars.cjs
 *
 * Page accounting (asserted by the generator — it throws if these do not close):
 *   128 placed across 7 sidebars
 *   34 withheld  — Handbook: internal-facing, retained in-repo but never published
 *                  (page-map §2b). `unlisted` is NOT protection; exclusion is by omission
 *                  here plus a post-build route/sitemap leak check.
 *   54 deferred  — body-less Mintlify `openapi:` stubs; the OpenAPI plugin now
 *                  regenerates these from the spec (M4 done) and the generated `apisidebar`
 *                  is spliced into `api-reference` — porting the stubs would only duplicate them.
 *   216 / 216 total — every legacy page has an explicit, intended fate.
 *
 * The Agent / Memory sidebars are authored in phases C4/C4b (net-new content), not generated here.
 */
const sidebars: SidebarsConfig = {
    "overview": [
            "overview/welcome",
            {
                    "type": "category",
                    "label": "About",
                    "collapsed": false,
                    "items": [
                            "about/i18n",
                            "about/changelog",
                            "about/license"
                    ]
            }
    ],
    "studio": [
            {
                    "type": "category",
                    "label": "Flows",
                    "collapsed": false,
                    "items": [
                            "flows/building-flows",
                            "flows/passing-data",
                            "flows/using-formulas",
                            "flows/formula-reference",
                            "flows/publishing-flows",
                            "flows/debugging-runs",
                            "flows/versioning",
                            "flows/known-limits"
                    ]
            },
            {
                    "type": "category",
                    "label": "MCP server",
                    "collapsed": false,
                    "items": [
                            "mcp/overview",
                            "mcp/tools"
                    ]
            },
      ...authoredAdditions["studio"],
    ],
    "admin-guide": [
            {
                    "type": "category",
                    "label": "Guides",
                    "collapsed": false,
                    "items": [
                            "admin-guide/guides/structure-projects",
                            "admin-guide/guides/manage-blocks",
                            "admin-guide/guides/sso",
                            "admin-guide/guides/manage-oauth2",
                            "admin-guide/guides/setup-ai-providers",
                            "admin-guide/guides/permissions",
                            "admin-guide/guides/event-streaming",
                            "admin-guide/guides/project-releases",
                            "admin-guide/guides/manage-concurrency"
                    ]
            },
            {
                    "type": "category",
                    "label": "Guides > SCIM",
                    "collapsed": false,
                    "items": [
                            "admin-guide/guides/scim/overview",
                            "admin-guide/guides/scim/providers/okta",
                            "admin-guide/guides/scim/providers/microsoft-entra-id"
                    ]
            },
            {
                    "type": "category",
                    "label": "Guides > Secret Managers",
                    "collapsed": false,
                    "items": [
                            "admin-guide/guides/secret-managers/overview",
                            "admin-guide/guides/secret-managers/aws",
                            "admin-guide/guides/secret-managers/hashicorp",
                            "admin-guide/guides/secret-managers/cyberark-conjur",
                            "admin-guide/guides/secret-managers/onepassword"
                    ]
            },
            {
                    "type": "category",
                    "label": "Security",
                    "collapsed": false,
                    "items": [
                            "admin-guide/security/practices"
                    ]
            },
            {
                    "type": "category",
                    "label": "Security > Audit Logs",
                    "collapsed": false,
                    "items": [
                            "admin-guide/security/audit-logs/overview",
                            "admin-guide/security/audit-logs/flow-created",
                            "admin-guide/security/audit-logs/flow-updated",
                            "admin-guide/security/audit-logs/flow-deleted",
                            "admin-guide/security/audit-logs/flow-published",
                            "admin-guide/security/audit-logs/flow-activated",
                            "admin-guide/security/audit-logs/flow-deactivated",
                            "admin-guide/security/audit-logs/connection-upserted",
                            "admin-guide/security/audit-logs/connection-deleted",
                            "admin-guide/security/audit-logs/flow-run-started",
                            "admin-guide/security/audit-logs/flow-run-finished",
                            "admin-guide/security/audit-logs/folder-created",
                            "admin-guide/security/audit-logs/folder-updated",
                            "admin-guide/security/audit-logs/folder-deleted",
                            "admin-guide/security/audit-logs/user-signed-in",
                            "admin-guide/security/audit-logs/user-signed-up",
                            "admin-guide/security/audit-logs/user-email-verified",
                            "admin-guide/security/audit-logs/user-password-reset",
                            "admin-guide/security/audit-logs/signing-key-created"
                    ]
            },
      ...authoredAdditions["admin-guide"],
    ],
    "deploy": [
            {
                    "type": "category",
                    "label": "Get Started",
                    "collapsed": false,
                    "items": [
                            "install/overview",
                            "install/options/docker",
                            "install/options/docker-compose"
                    ]
            },
            {
                    "type": "category",
                    "label": "Get Started > Other Options",
                    "collapsed": false,
                    "items": [
                            "install/options/helm",
                            "install/options/easypanel",
                            "install/options/aws",
                            "install/options/gcp",
                            "install/options/railway",
                            "install/options/elestio"
                    ]
            },
            {
                    "type": "category",
                    "label": "Configuration",
                    "collapsed": false,
                    "items": [
                            "install/configuration/overview",
                            "install/configuration/environment-variables",
                            "install/configuration/hardware",
                            "install/configuration/breaking-changes",
                            "install/configuration/telemetry"
                    ]
            },
            {
                    "type": "category",
                    "label": "Guides",
                    "collapsed": false,
                    "items": [
                            "install/guides/setup-ssl",
                            "install/guides/setup-opentelemetry",
                            "install/guides/setup-s3",
                            "install/guides/separate-workers",
                            "install/guides/setup-app-webhooks",
                            "install/guides/rollback"
                    ]
            },
            {
                    "type": "category",
                    "label": "Troubleshooting",
                    "collapsed": false,
                    "items": [
                            "install/troubleshooting/bullboard",
                            "install/troubleshooting/reset-password",
                            "install/troubleshooting/truncated-logs",
                            "install/troubleshooting/websocket-issues"
                    ]
            },
            {
                    "type": "category",
                    "label": "Architecture",
                    "collapsed": false,
                    "items": [
                            "install/architecture/overview",
                            "install/architecture/workers",
                            "install/architecture/sandboxing",
                            "install/architecture/durable-execution",
                            "install/architecture/waitpoints",
                            "install/architecture/network-security",
                            "install/architecture/block-syncing",
                            "install/architecture/benchmark"
                    ]
            }
    ],
    "embedding": [
            {
                    "type": "category",
                    "label": "Essentials",
                    "collapsed": false,
                    "items": [
                            "embedding/overview",
                            "embedding/configure-embedding",
                            "embedding/provision-users",
                            "embedding/embed-builder"
                    ]
            },
            {
                    "type": "category",
                    "label": "Misc",
                    "collapsed": false,
                    "items": [
                            "embedding/customize-blocks",
                            "embedding/embed-connections",
                            "embedding/navigation",
                            "embedding/predefined-connection",
                            "embedding/sdk-changelog",
                            "embedding/sdk-server-requests"
                    ]
            }
    ],
    "build-blocks": [
            {
                    "type": "category",
                    "label": "Build a Block",
                    "collapsed": false,
                    "items": [
                            "build-blocks/building-blocks/overview",
                            "build-blocks/building-blocks/start-building",
                            "build-blocks/building-blocks/setup-fork",
                            "build-blocks/building-blocks/development-setup",
                            "build-blocks/building-blocks/block-definition",
                            "build-blocks/building-blocks/block-authentication",
                            "build-blocks/building-blocks/create-action",
                            "build-blocks/building-blocks/create-trigger"
                    ]
            },
            {
                    "type": "category",
                    "label": "Build a Block > Sharing Blocks",
                    "collapsed": false,
                    "items": [
                            "build-blocks/sharing-blocks/overview",
                            "build-blocks/sharing-blocks/contribute",
                            "build-blocks/sharing-blocks/community",
                            "build-blocks/sharing-blocks/private"
                    ]
            },
            {
                    "type": "category",
                    "label": "Block Reference",
                    "collapsed": false,
                    "items": [
                            "build-blocks/block-reference/authentication",
                            "build-blocks/block-reference/properties",
                            "build-blocks/block-reference/properties-validation",
                            "build-blocks/block-reference/flow-control",
                            "build-blocks/block-reference/persistent-storage",
                            "build-blocks/block-reference/files",
                            "build-blocks/block-reference/external-libraries",
                            "build-blocks/block-reference/block-versioning",
                            "build-blocks/block-reference/examples",
                            "build-blocks/block-reference/custom-api-calls",
                            "build-blocks/block-reference/i18n"
                    ]
            },
            {
                    "type": "category",
                    "label": "Block Reference > Triggers",
                    "collapsed": false,
                    "items": [
                            "build-blocks/block-reference/triggers/overview",
                            "build-blocks/block-reference/triggers/polling-trigger",
                            "build-blocks/block-reference/triggers/webhook-trigger"
                    ]
            },
            {
                    "type": "category",
                    "label": "Misc",
                    "collapsed": false,
                    "items": [
                            "build-blocks/misc/build-block",
                            "build-blocks/misc/publish-block",
                            "build-blocks/misc/blocks-ci-cd",
                            "build-blocks/misc/migrate-nx-to-turbo",
                            "build-blocks/misc/private-fork",
                            "build-blocks/misc/testing-blocks",
                            "build-blocks/misc/dev-container",
                            "build-blocks/misc/codespaces"
                    ]
            }
    ],
    "api-reference": [
            {
                    "type": "category",
                    "label": "Get Started",
                    "collapsed": false,
                    "items": [
                            "endpoints/overview"
                    ]
            },
      ...apiSidebar,
    ],
  ...authoredSidebars,
};

export default sidebars;
