encryptionsalt: v1:icXg2cmIvSc=:v1:y8+4YhdMCPPDY26J:5cNYmimH353n8sjUDDc6srvcPgb+8Q==
config:
  intellisper:environment: "prod"
  intellisper:apEncryptionKey:  
  intellisper:apJwtSecret: 
  intellisper:deployLocalBuild: "true"
  intellisper:repoName: "intellisper-prod-repo"
  intellisper:containerCpu: "512"
  intellisper:containerMemory: "1024"
  intellisper:containerInstances: "1"
  intellisper:usePostgres: "true"
  intellisper:dbInstanceClass: "db.t3.small"
  intellisper:dbIsPublic: "false"
  intellisper:dbPassword:
    secure: v1:MXNSOcqZCp10X2PX:mU2iTrcETjdisk8FkD5yHLJYUxRei/9l
  intellisper:dbUsername: "postgres"
  intellisper:useRedis: "true"
  intellisper:redisNodeType: "cache.t3.small"
  aws:region: "us-east-1"
